/auto_aim_node:
    ros__parameters:
        armor_is_red: false
        camera_name: "mv_camera"
        imu_name: "imu/data_raw"
        xml_path: "./contrib_modules/rm_hero_auto_aim/resource/mnist_svm.xml"
        best_effort_qos: true
        robot_color: "blue"
        auto_start: false